"""initial schema: extensions, tables, indexes, RLS, grants

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-25

Hand-written (not autogenerated). Reviewed against app/database/models.
Run from backend/: `uv run alembic upgrade head`.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Keep in sync with app.database.models.constants.EMBEDDING_DIMENSIONS
EMBEDDING_DIMENSIONS = 1536

USER_TABLES = (
    "profiles",
    "chat_threads",
    "chat_messages",
    "message_citations",
)


def upgrade() -> None:
    # --- extensions ---------------------------------------------------------
    # pgvector lives in Supabase's `extensions` schema; no-op if already enabled.
    op.execute("CREATE SCHEMA IF NOT EXISTS extensions")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions")

    # --- tables -------------------------------------------------------------
    op.create_table(
        "profiles",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
    )
    op.create_table(
        "source_documents",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("company", sa.String(length=200), nullable=False),
        sa.Column("filing_type", sa.String(length=16), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("accession_number", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint(
            "accession_number", name=op.f("uq_source_documents_accession_number")
        ),
    )
    op.create_index(
        op.f("ix_source_documents_ticker"),
        "source_documents",
        ["ticker"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_documents_fiscal_year"),
        "source_documents",
        ["fiscal_year"],
        unique=False,
    )
    op.create_table(
        "chat_threads",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_threads")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
            name=op.f("fk_chat_threads_user_id_profiles"),
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        op.f("ix_chat_threads_user_id"), "chat_threads", ["user_id"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("thread_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("ui_message", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["chat_threads.id"],
            name=op.f("fk_chat_messages_thread_id_chat_threads"),
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "role::text = ANY (ARRAY['user'::text, 'assistant'::text])",
            name=op.f("ck_chat_messages_role_allowed"),
        ),
    )
    op.create_index(
        op.f("ix_chat_messages_thread_id"),
        "chat_messages",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("document_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=200), nullable=True),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column(
            "embedding",
            Vector(EMBEDDING_DIMENSIONS),
            nullable=True,
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', chunk_text)", persisted=True),
            nullable=True,
        ),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_documents.id"],
            name=op.f("fk_document_chunks_document_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "document_id",
            "chunk_index",
            name=op.f("uq_document_chunks_document_id_chunk_index"),
        ),
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"),
        "document_chunks",
        ["document_id"],
        unique=False,
    )
    # Hybrid-retrieval indexes, written explicitly (see architecture.md):
    # HNSW for pgvector cosine similarity, GIN for tsvector + metadata JSON.
    op.create_index(
        "ix_document_chunks_embedding_hnsw",
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_document_chunks_search_vector_gin",
        "document_chunks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_document_chunks_metadata_gin",
        "document_chunks",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "message_citations",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("message_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("chunk_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("document_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=200), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_citations")),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["chat_messages.id"],
            name=op.f("fk_message_citations_message_id_chat_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_message_citations_chunk_id_document_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_documents.id"],
            name=op.f("fk_message_citations_document_id_source_documents"),
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        op.f("ix_message_citations_message_id"),
        "message_citations",
        ["message_id"],
        unique=False,
    )

    # --- row level security ---------------------------------------------------
    # Ingestion tables (source_documents, document_chunks) get no policies:
    # writes are backend-only via the service role; user-scoped reads go
    # through the backend API, not PostgREST.
    rls_statements = [
        "ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY",
        "ALTER TABLE public.chat_threads ENABLE ROW LEVEL SECURITY",
        "ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY",
        "ALTER TABLE public.message_citations ENABLE ROW LEVEL SECURITY",
        # profiles: read own row; creation happens backend-side with the
        # service role (bypasses RLS), so no insert/update policy is needed.
        """
        CREATE POLICY profiles_select_own ON public.profiles
        FOR SELECT TO authenticated
        USING (auth.uid() = id)
        """,
        # chat threads: full CRUD on own threads.
        """
        CREATE POLICY chat_threads_all_own ON public.chat_threads
        FOR ALL TO authenticated
        USING (auth.uid() = user_id)
        WITH CHECK (auth.uid() = user_id)
        """,
        # chat messages: access via the owning thread.
        """
        CREATE POLICY chat_messages_all_own ON public.chat_messages
        FOR ALL TO authenticated
        USING (
            EXISTS (
                SELECT 1 FROM public.chat_threads AS t
                WHERE t.id = thread_id AND t.user_id = auth.uid()
            )
        )
        WITH CHECK (
            EXISTS (
                SELECT 1 FROM public.chat_threads AS t
                WHERE t.id = thread_id AND t.user_id = auth.uid()
            )
        )
        """,
        # citations: read-only for the message owner; writes go through the
        # backend with the service role after citation validation.
        """
        CREATE POLICY message_citations_select_own ON public.message_citations
        FOR SELECT TO authenticated
        USING (
            EXISTS (
                SELECT 1
                FROM public.chat_messages AS m
                JOIN public.chat_threads AS t ON t.id = m.thread_id
                WHERE m.id = message_id AND t.user_id = auth.uid()
            )
        )
        """,
    ]
    for statement in rls_statements:
        op.execute(" ".join(statement.split()))

    # --- grants ---------------------------------------------------------------
    # authenticated: CRUD on user-owned tables, read-only on the corpus.
    op.execute(
        f"GRANT SELECT, INSERT, UPDATE, DELETE ON "
        f"{', '.join(f'public.{name}' for name in USER_TABLES)} TO authenticated"
    )
    op.execute(
        "GRANT SELECT ON public.source_documents, public.document_chunks "
        "TO authenticated"
    )
    # service_role bypasses RLS; grants cover future tables too.
    op.execute("GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role")


def downgrade() -> None:
    # message_citations → chat_messages → chat_threads (with profiles last).
    op.drop_index(
        op.f("ix_message_citations_message_id"), table_name="message_citations"
    )
    op.drop_table("message_citations")
    op.drop_index(
        "ix_document_chunks_metadata_gin", table_name="document_chunks"
    )
    op.drop_index(
        "ix_document_chunks_search_vector_gin", table_name="document_chunks"
    )
    op.drop_index(
        "ix_document_chunks_embedding_hnsw", table_name="document_chunks"
    )
    op.drop_index(
        op.f("ix_document_chunks_document_id"), table_name="document_chunks"
    )
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_chat_messages_thread_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_chat_threads_user_id"), table_name="chat_threads")
    op.drop_table("chat_threads")
    op.drop_index(
        op.f("ix_source_documents_fiscal_year"), table_name="source_documents"
    )
    op.drop_index(op.f("ix_source_documents_ticker"), table_name="source_documents")
    op.drop_table("source_documents")
    op.drop_table("profiles")
    # The vector extension is shared infrastructure; leave it installed.
